//用户列表
export const USER_LIST = 'cam2/ListUsers'
export const POLICY_LIST = 'cam2/ListPolicies'
export const USER_GROUP = 'cam2/ListGroups'
export const DELETE_USER = 'cam2/DeleteUser'
export const QUERY_USER = 'cam2/GetUser'
export const POLICY_USER = 'cam2/AttachUserPolicy'
export const ADD_USER = 'cam2/AddUser'
export const REMOVEBIND_USER = 'cam2/DetachUserPolicy'
export const REMOVEGROUP_USER = 'cam2/DeleteGroup'
export const UPDATA_USER = 'cam2/UpdateUser'
export const RELATE_USER = 'cam2/ListGroupsForUser'
export const QUERY_POLICY = 'cam2/ListAttachedUserPolicies'
export const CREATE_USER = 'cam2/CreateGroup'
export const ADD_USERTOGROUP = 'cam2/AddUserToGroup'
export const DEL_USERTOGROUP = 'cam2/RemoveUserFromGroup'
export const GROUP_POLICY = 'cam2/ListAttachedGroupPolicies'
export const CREATE_SAML = 'cam2/CreateSAMLProvider'
export const GET_SAML = 'cam2/GetSAMLProvider'
export const GROUP_USERS = 'cam2/ListUsersForGroup'
export const DELE_GROUP = 'cam2/DeleteGroup'
export const ADD_GROUPTOLIST = 'cam2/AddUserToGroup'
export const LIST_Providers = 'cam2/ListSAMLProviders'
export const ATTACH_GROUP = 'cam2/AttachGroupPolicy'
export const GET_GROUP = 'cam2/GetGroup'
export const UPDATA_GROUP = 'cam2/UpdateGroup'
export const DETACH_POLICY = 'cam2/DetachGroupPolicy'

//策略
export const LIST_ENPOLICY = 'cam2/ListEntitiesForPolicy'
export const DELETE_POLICY = 'cam2/DeletePolicy'
export const GET_POLICY = 'cam2/GetPolicy'

//角色
export const GET_ROLE = 'cam2/GetRole'
export const LIST_ATTACHE = 'cam2/ListAttachedRolePolicies'
export const DEACH_ROLE = 'cam2/DetachRolePolicy'
export const UPDATE_ROLE = 'cam2/UpdateRoleDescription'
export const UPDATE_ASSUME = 'cam2/UpdateAssumeRolePolicy'
export const DESCRIB_ROLE = 'cam2/DescribeRoleList'
export const DELETE_ROLE = 'cam2/DeleteRole'
export const CREATE_ROLE = 'cam2/CreateRole'
export const ATTACH_ROLE = 'cam2/AttachRolePolicy'

