let nameComparison = {
  "Canada": "加拿大",
  "Turkmenistan": "土庫曼",
  "Saint Helena": "聖赫勒拿",
  "Lao PDR": "寮國",
  "Lithuania": "立陶宛",
  "Cambodia": "柬埔寨",
  "Ethiopia": "衣索比亞",
  "Faeroe Is.": "法羅群島",
  "Swaziland": "史瓦濟蘭",
  "Palestine": "巴勒斯坦",
  "Belize": "貝里斯",
  "Argentina": "阿根廷",
  "Bolivia": "玻利維亞",
  "Cameroon": "喀麥隆",
  "Burkina Faso": "布吉納法索",
  "Aland": "奧蘭群島",
  "Bahrain": "巴林",
  "Saudi Arabia": "沙烏地阿拉伯",
  "Fr. Polynesia": "法屬波利尼西亞",
  "Cape Verde": "維德角",
  "W. Sahara": "西撒哈拉",
  "Slovenia": "斯洛維尼亞",
  "Guatemala": "瓜地馬拉",
  "Guinea": "幾內亞",
  "Dem. Rep. Congo": "剛果民主共和國",
  "Germany": "德國",
  "Spain": "西班牙",
  "Liberia": "賴比瑞亞",
  "Netherlands": "荷蘭",
  "Jamaica": "牙買加",
  "Solomon Is.": "索羅門群島",
  "Oman": "阿曼",
  "Tanzania": "坦尚尼亞聯合共和國",
  "Costa Rica": "哥斯大黎加",
  "Isle of Man": "曼島",
  "Gabon": "加彭",
  "Niue": "紐埃",
  "Bahamas": "巴哈馬",
  "New Zealand": "紐西蘭",
  "Yemen": "葉門",
  "Jersey": "澤西島",
  "Pakistan": "巴基斯坦",
  "Albania": "阿爾巴尼亞",
  "Samoa": "薩摩亞",
  "Czech Rep.": "捷克",
  "United Arab Emirates": "阿拉伯聯合大公國",
  "Guam": "關島",
  "India": "印度",
  "Azerbaijan": "亞塞拜然",
  "N. Mariana Is.": "北馬里亞納群島",
  "Lesotho": "賴索托",
  "Kenya": "肯亞",
  "Belarus": "白俄羅斯",
  "Tajikistan": "塔吉克",
  "Turkey": "土耳其",
  "Afghanistan": "阿富汗",
  "Bangladesh": "孟加拉國",
  "Mauritania": "茅利塔尼亞",
  "Dem. Rep. Korea": "朝鮮",
  "Saint Lucia": "聖露西亞",
  "Br. Indian Ocean Ter.": "英屬印度洋領地",
  "Mongolia": "蒙古",
  "France": "法國",
  "Cura?ao": "庫拉索島",
  "S. Sudan": "南蘇丹",
  "Rwanda": "盧安達",
  "Slovakia": "斯洛伐克",
  "Somalia": "索馬利亞",
  "Peru": "秘魯",
  "Vanuatu": "萬那杜",
  "Norway": "挪威",
  "Malawi": "馬拉維",
  "Benin": "貝南",
  "St. Vin. and Gren.": "聖文森及格瑞那丁",
  "Korea": "韓國",
  "Singapore": "新加坡",
  "Montenegro": "黑山共和國",
  "Cayman Is.": "開曼群島",
  "Togo": "多哥",
  "China": "中國",
  "Heard I. and McDonald Is.": "赫德島和麥克唐納群島",
  "Armenia": "亞美尼亞",
  "Falkland Is.": "馬爾維納斯群島（福克蘭）",
  "Ukraine": "烏克蘭",
  "Ghana": "迦納",
  "Tonga": "湯加",
  "Finland": "芬蘭",
  "Libya": "利比亞",
  "Dominican Rep.": "多米尼加",
  "Indonesia": "印度尼西亞",
  "Mauritius": "模里西斯",
  "Eq. Guinea": "赤道幾內亞",
  "Sweden": "瑞典",
  "Vietnam": "越南",
  "Mali": "馬里",
  "Russia": "俄羅斯",
  "Bulgaria": "保加利亞",
  "United States": "美國",
  "Romania": "羅馬尼亞",
  "Angola": "安哥拉",
  "Chad": "查德",
  "South Africa": "南非",
  "Fiji": "斐濟",
  "Liechtenstein": "列支敦斯登",
  "Malaysia": "馬來西亞",
  "Austria": "奧地利",
  "Mozambique": "莫三比克",
  "Uganda": "烏干達",
  "Japan": "日本",
  "Niger": "尼日",
  "Brazil": "巴西",
  "Kuwait": "科威特",
  "Panama": "巴拿馬",
  "Guyana": "蓋亞那",
  "Madagascar": "馬達加斯加",
  "Luxembourg": "盧森堡",
  "American Samoa": "美屬薩摩亞",
  "Andorra": "安道爾",
  "Ireland": "愛爾蘭",
  "Italy": "義大利",
  "Nigeria": "奈及利亞",
  "Turks and Caicos Is.": "特克斯和凱科斯群島",
  "Ecuador": "厄瓜多",
  "U.S. Virgin Is.": "美屬維爾京群島",
  "Brunei": "汶萊",
  "Australia": "澳大利亞",
  "Iran": "伊朗",
  "Algeria": "阿爾及利亞",
  "El Salvador": "薩爾瓦多",
  "C?te d'Ivoire": "象牙海岸",
  "Chile": "智利",
  "Puerto Rico": "波多黎各",
  "Belgium": "比利時",
  "Thailand": "泰國",
  "Haiti": "海地",
  "Iraq": "伊拉克",
  "S?o Tomé and Principe": "聖多美和普林西比",
  "Sierra Leone": "獅子山",
  "Georgia": "喬治亞",
  "Denmark": "丹麥",
  "Philippines": "菲律賓",
  "S. Geo. and S. Sandw. Is.": "南喬治亞島和南桑威奇群島",
  "Moldova": "摩爾多瓦",
  "Morocco": "摩洛哥",
  "Namibia": "納米比亞",
  "Malta": "馬爾他",
  "Guinea-Bissau": "幾內亞比索",
  "Kiribati": "吉里巴斯",
  "Switzerland": "瑞士",
  "Grenada": "格瑞那達",
  "Seychelles": "塞席爾",
  "Portugal": "葡萄牙",
  "Estonia": "愛沙尼亞",
  "Uruguay": "烏拉圭",
  "Antigua and Barb.": "安地卡及巴布達",
  "Lebanon": "黎巴嫩",
  "Uzbekistan": "烏茲別克",
  "Tunisia": "突尼西亞",
  "Djibouti": "吉布地",
  "Greenland": "格陵蘭",
  "Timor-Leste": "東帝汶",
  "Dominica": "多米尼克",
  "Colombia": "哥倫比亞",
  "Burundi": "蒲隆地",
  "Bosnia and Herz.": "波士尼亞赫塞哥維納",
  "Cyprus": "塞普勒斯",
  "Barbados": "巴貝多",
  "Qatar": "卡達",
  "Palau": "帛琉",
  "Bhutan": "不丹",
  "Sudan": "蘇丹",
  "Nepal": "尼泊爾",
  "Micronesia": "密克羅尼西亞",
  "Bermuda": "百慕大",
  "Suriname": "蘇利南",
  "Venezuela": "委內瑞拉",
  "Israel": "以色列",
  "St. Pierre and Miquelon": "聖皮埃爾和密克隆群島",
  "Central African Rep.": "中非共和國",
  "Iceland": "冰島",
  "Zambia": "尚比亞",
  "Senegal": "塞內加爾",
  "Papua New Guinea": "巴布亞紐幾內亞",
  "Trinidad and Tobago": "特立尼達和多巴哥",
  "Zimbabwe": "辛巴威",
  "Jordan": "約旦",
  "Gambia": "甘比亞",
  "Kazakhstan": "哈薩克",
  "Poland": "波蘭",
  "Eritrea": "厄利垂亞",
  "Kyrgyzstan": "吉爾吉斯斯坦",
  "Montserrat": "蒙特塞拉特",
  "New Caledonia": "新喀里多尼亞",
  "Macedonia": "馬其頓",
  "Paraguay": "巴拉圭",
  "Latvia": "拉脫維亞",
  "Hungary": "匈牙利",
  "Syria": "敘利亞",
  "Honduras": "宏都拉斯",
  "Myanmar": "緬甸",
  "Mexico": "墨西哥",
  "Egypt": "埃及",
  "Nicaragua": "尼加拉瓜",
  "Cuba": "古巴",
  "Serbia": "塞爾維亞",
  "Comoros": "葛摩",
  "United Kingdom": "英國",
  "Fr. S. Antarctic Lands": "南極洲",
  "Congo": "剛果共和國",
  "Greece": "希臘",
  "Sri Lanka": "斯里蘭卡",
  "Croatia": "克羅埃西亞",
  "Botswana": "波札那",
  "Siachen Glacier": "錫亞琴冰川地區"
}

export default nameComparison;